spring:
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/ps_dev
    username: ps_dev
    password: ps_dev

  data:
    redis:
      host: redis
      port: 6379
      database: 0

server:
  port: 8091
